# Generated by Django 4.2.11 on 2025-10-10 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='active_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 10, 18, 51, 50, 60217, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default='Title', max_length=200),
        ),
    ]
